from execution_engine.omop.cohort import PopulationInterventionPairExpr, Recommendation
from execution_engine.omop.criterion.visit_occurrence import PatientsActiveDuringPeriod

from digipod.criterion.non_pharma_measures import *

#######################################################################################################################


recommendation = Recommendation(
    expr=MinCount(
        #####################################################
        # BUNDLE 1
        #####################################################
        And(
            PopulationInterventionPairExpr(
                population_expr=And(
                    Not(anyDementiaBeforeDayOfSurgery), anyCognitiveImpairment
                ),
                intervention_expr=PostOperative(facesAnxietyScoreAssessed),
                name="RecPlanAssessFASPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanAssessFASPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=And(
                    anyCognitiveImpairment,
                    Or(anyDementiaBeforeSurgery, anyPositiveDeliriumTest),
                ),
                intervention_expr=And(
                    PostOperative(nonPharmaAnxietyIntervention),
                    Or(
                        PostOperative(verbalAnxietyManagement),
                        PostOperative(triggerAvoidanceForAnxiety),
                        PostOperative(socialServiceInterview),
                        PostOperative(palliativeCareConsultation),
                        PostOperative(familyInvolvementInCare),
                        PostOperative(individualizedPatientEducation),
                        PostOperative(identificationOfCarePreferences),
                    ),
                ),
                name="RecPlanNonPharmaAnxietyMeasuresInPatWithDementiaOrDeliriumPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanNonPharmaAnxietyMeasuresInPatWithDementiaOrDeliriumPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=And(
                    And(Not(anyDementiaBeforeDayOfSurgery), anyCognitiveImpairment),
                    Or(
                        PreFacesScalePostOp(nudescLt2),
                        PreFacesScalePostOp(nudescNegative),
                        PreFacesScalePostOp(nudescWeaklyPositive),
                        PreFacesScalePostOp(icdscLt4),
                        PreFacesScalePostOp(icdscNegative),
                        PreFacesScalePostOp(icdscWeaklyPositive),
                        PreFacesScalePostOp(camNegative),
                        PreFacesScalePostOp(drsLt12),
                        PreFacesScalePostOp(drsNegative),
                        PreFacesScalePostOp(drsWeaklyPositive),
                        PreFacesScalePostOp(dosLt3),
                        PreFacesScalePostOp(dosNegative),
                        PreFacesScalePostOp(dosWeaklyPositive),
                        PreFacesScalePostOp(tdcamNegative),
                        PreFacesScalePostOp(camicuNegative),
                        PreFacesScalePostOp(ddsLt8),
                        PreFacesScalePostOp(ddsNegative),
                        PreFacesScalePostOp(ddsWeaklyPositive),
                        PreFacesScalePostOp(FourAtLt4),
                        PreFacesScalePostOp(FourAtNegative),
                        PreFacesScalePostOp(FourAtWeaklyPositive),
                    ),
                    Or(
                        Not(PreFacesScaleOnAssessmentDayPostOp(nuDescGte2)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(nuDescPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(icdscGte4)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(icdscPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(camPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(drsGte12)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(drsPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(dosGte3)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(dosPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(tdcamPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(camicuPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(ddsGte7)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(ddsPositive)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(FourAtGte4)),
                        Not(PreFacesScaleOnAssessmentDayPostOp(FourAtPositive)),
                    ),
                    facesAnxietyScoreGte2,
                ),
                intervention_expr=And(
                    OnFacesScaleAssessmentDayPostOp(nonPharmaAnxietyIntervention),
                    Or(
                        OnFacesScaleAssessmentDayPostOp(verbalAnxietyManagement),
                        OnFacesScaleAssessmentDayPostOp(triggerAvoidanceForAnxiety),
                        OnFacesScaleAssessmentDayPostOp(socialServiceInterview),
                        OnFacesScaleAssessmentDayPostOp(palliativeCareConsultation),
                        OnFacesScaleAssessmentDayPostOp(familyInvolvementInCare),
                        OnFacesScaleAssessmentDayPostOp(individualizedPatientEducation),
                        OnFacesScaleAssessmentDayPostOp(
                            identificationOfCarePreferences
                        ),
                    ),
                ),
                name="RecPlanNonPharmaMeasuresForAnxietyInPatWithPositiveFASPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanNonPharmaMeasuresForAnxietyInPatWithPositiveFASPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
        ),
        #####################################################
        # BUNDLE 2
        #####################################################
        And(
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=MinCount(
                    PostOperative(cognitiveStimulationProcedure),
                    Or(
                        PostOperative(readingActivity),
                        PostOperative(conversationForCognition),
                        PostOperative(boardGamesOrPuzzles),
                        PostOperative(singingActivity),
                        PostOperative(cognitiveAssessment),
                    ),
                    threshold=1,
                ),
                name="RecPlanCognitiveStimulationPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanCognitiveStimulationPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=MinCount(
                    PostOperative(communicationAidProvision),
                    Or(
                        PostOperative(spectacleSupply),
                        PostOperative(hearingAidProvision),
                        PostOperative(assistiveWritingDevice),
                        PostOperative(removableDentureProvision),
                        PostOperative(interpreterServiceRequest),
                        PostOperative(communicationAssistiveDevice),
                    ),
                    threshold=1,
                ),
                name="RecPlanProvisionOfCommunicationAidsPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanProvisionOfCommunicationAidsPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=MinCount(
                    PostOperative(supportCircadianRhythm),
                    Or(
                        PostOperative(sleepingMaskProvision),
                        PostOperative(earplugsAtNight),
                        PostOperative(noiseReduction),
                        PostOperative(lightExposureDaytime),
                        PostOperative(reduceNightLight),
                        PostOperative(closePatientRoomDoor),
                        PostOperative(promoteSleepHygiene),
                        PostOperative(onlyEmergencyAtNight),
                        PostOperative(otherSleepHygieneInterventions),
                    ),
                    threshold=1,
                ),
                name="RecPlanNonPharmaInterventionsSupportingCircardianRhythmPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanNonPharmaInterventionsSupportingCircardianRhythmPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=MinCount(
                    PostOperative(realityOrientation),
                    Or(
                        PostOperative(wearableWatch),
                        PostOperative(calendarDevice),
                        PostOperative(printedMaterial),
                        PostOperative(televisionDevice),
                        PostOperative(radioDevice),
                        PostOperative(otherMediaExposure),
                    ),
                    threshold=1,
                ),
                name="RecPlanDocumentProvisionOrientationAidPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentProvisionOrientationAidPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
        ),
        #####################################################
        # BUNDLE 3
        #####################################################
        And(
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=PostOperative(mobilizationAbilityObservation),
                name="RecPlanDocumentMobilizationAbilitiesPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentMobilizationAbilitiesPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=And(anyCognitiveImpairment, mobility),
                intervention_expr=ExactCount(
                    PostOperative(physiatricJointMobilization),
                    Or(
                        PostOperative(contraindicationObservation),
                        PostOperative(patientNonCompliance),
                        PostOperative(lackOfEnergyCondition),
                        PostOperative(anxietyCondition),
                        PostOperative(painCondition),
                        PostOperative(exhaustionObservation),
                        PostOperative(dizzinessCondition),
                        PostOperative(reasonAndJustificationObservation),
                    ),
                    threshold=1,
                ),
                name="RecPlanDocumentMobilizePatientOrDocumentWhyNoMobilizationPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentMobilizePatientOrDocumentWhyNoMobilizationPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
        ),
        #####################################################
        # BUNDLE 4
        #####################################################
        And(
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=PostOperative(selfFeedingAbility),
                name="RecPlanDocumentFeedingAbilitiesPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentFeedingAbilitiesPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=And(anyCognitiveImpairment, selfFeeding),
                intervention_expr=ExactCount(
                    PostOperative(enteralFeeding),
                    Or(
                        PostOperative(contraindicationObservation),
                        PostOperative(ivFeeding),
                        PostOperative(aspirationRisk),
                        PostOperative(abnormalDeglutition),
                        PostOperative(painCondition),
                        PostOperative(lossOfAppetite),
                        PostOperative(digestiveReflux),
                        PostOperative(nauseaAndVomiting),
                    ),
                    threshold=1,
                ),
                name="RecPlanDocumentFeedEnterallyPatientOrDocumentWhyNoFeedingPostOP",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentFeedEnterallyPatientOrDocumentWhyNoFeedingPostOP",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=PostOperative(deglutition),
                name="RecPlanDocumentDeglutitionAbilitiesPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDocumentDeglutitionAbilitiesPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=And(anyCognitiveImpairment, deglutitionMeasurement),
                intervention_expr=And(
                    OnFacesScaleAssessmentDayPostOp(dysphagiaTherapy),
                    OnFacesScaleAssessmentDayPostOp(nutritionalRegimeModification),
                ),
                name="RecPlanDeglutitionRelatedInterventionsPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanDeglutitionRelatedInterventionsPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
            PopulationInterventionPairExpr(
                population_expr=anyCognitiveImpairment,
                intervention_expr=PostOperative(mouthCare),
                name="RecPlanOralCareRelatedInterventionsPostoperatively",
                url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanOralCareRelatedInterventionsPostoperatively",
                base_criterion=PatientsActiveDuringPeriod(),
            ),
        ),
        threshold=4,
    ),
    base_criterion=PatientsActiveDuringPeriod(),
    name="RecCollBundleOfNonPharmaMeasuresPostOPInAdultsAtRiskForPOD",
    title="Recommendation Collection: Perform a bundle of non-pharmacological interventions once a day postoperatively in different populations of 'Adult Surgical Patients At Risk For POD'",
    url="https://fhir.charite.de/digipod/PlanDefinition/RecCollBundleOfNonPharmaMeasuresPostOPInAdultsAtRiskForPOD",
    version="0.1.0",
    description="Recommendation collection for different populations of adult patients that were at risk for postoperative delirium before undergoing a surgical intervention of any type independently of the type of anesthesia: Perform different non-pharmacological interventions (related to anxiety, nutrition, mobilization, and cognition) as bundle once a day postoperatively until discharge.",
    package_version="latest",
)
