from execution_engine.omop.cohort import PopulationInterventionPairExpr, Recommendation
from execution_engine.omop.concepts import Concept
from execution_engine.omop.criterion.procedure_occurrence import ProcedureOccurrence
from execution_engine.omop.criterion.visit_occurrence import PatientsActiveDuringPeriod
from execution_engine.util.logic import *

from digipod.criterion.non_pharma_measures import (
    BeforeFirstDexAdministration,
    FourAtGte4,
    FourAtLt4,
    FourAtNegative,
    FourAtPositive,
    FourAtWeaklyPositive,
    IntraOrPostOperative,
    anyDementiaBeforeSurgery,
    camicuNegative,
    camicuPositive,
    camNegative,
    camPositive,
    ddsGte7,
    ddsLt8,
    ddsNegative,
    ddsPositive,
    ddsWeaklyPositive,
    dosGte3,
    dosLt3,
    dosNegative,
    dosPositive,
    dosWeaklyPositive,
    drsGte12,
    drsLt12,
    drsNegative,
    drsPositive,
    drsWeaklyPositive,
    icdscGte4,
    icdscLt4,
    icdscNegative,
    icdscPositive,
    icdscWeaklyPositive,
    nudescGte2,
    nudescLt2,
    nudescNegative,
    nudescPositive,
    nudescWeaklyPositive,
    tdcamNegative,
    tdcamPositive,
)
from digipod.criterion.patients import AdultPatients

prophylacticDexmedetomidine = ProcedureOccurrence(
    static=False,
    concept=Concept(
        concept_id=2000000024,
        concept_name="Administration of prophylactic dexmedetomidine",
        concept_code="024",
        domain_id="Procedure",
        vocabulary_id="DIGIPOD",
        concept_class_id="Custom",
        standard_concept=None,
        invalid_reason=None,
    ),
    value=None,
)

recommendation = Recommendation(
    expr=And(
        PopulationInterventionPairExpr(
            population_expr=And(
                And(
                    AdultPatients(),
                    Not(anyDementiaBeforeSurgery),
                ),
                Or(
                    BeforeFirstDexAdministration(nudescLt2),
                    BeforeFirstDexAdministration(nudescNegative),
                    BeforeFirstDexAdministration(nudescWeaklyPositive),
                    BeforeFirstDexAdministration(icdscLt4),
                    BeforeFirstDexAdministration(icdscNegative),
                    BeforeFirstDexAdministration(icdscWeaklyPositive),
                    BeforeFirstDexAdministration(camNegative),
                    BeforeFirstDexAdministration(drsLt12),
                    BeforeFirstDexAdministration(drsNegative),
                    BeforeFirstDexAdministration(drsWeaklyPositive),
                    BeforeFirstDexAdministration(dosLt3),
                    BeforeFirstDexAdministration(dosNegative),
                    BeforeFirstDexAdministration(dosWeaklyPositive),
                    BeforeFirstDexAdministration(tdcamNegative),
                    BeforeFirstDexAdministration(camicuNegative),
                    BeforeFirstDexAdministration(ddsLt8),
                    BeforeFirstDexAdministration(ddsNegative),
                    BeforeFirstDexAdministration(ddsWeaklyPositive),
                    BeforeFirstDexAdministration(FourAtLt4),
                    BeforeFirstDexAdministration(FourAtNegative),
                    BeforeFirstDexAdministration(FourAtWeaklyPositive),
                ),
                Or(
                    Not(BeforeFirstDexAdministration(nudescGte2)),
                    Not(BeforeFirstDexAdministration(nudescPositive)),
                    Not(BeforeFirstDexAdministration(icdscGte4)),
                    Not(BeforeFirstDexAdministration(icdscPositive)),
                    Not(BeforeFirstDexAdministration(camPositive)),
                    Not(BeforeFirstDexAdministration(drsGte12)),
                    Not(BeforeFirstDexAdministration(drsPositive)),
                    Not(BeforeFirstDexAdministration(dosGte3)),
                    Not(BeforeFirstDexAdministration(dosPositive)),
                    Not(BeforeFirstDexAdministration(tdcamPositive)),
                    Not(BeforeFirstDexAdministration(camicuPositive)),
                    Not(BeforeFirstDexAdministration(ddsGte7)),
                    Not(BeforeFirstDexAdministration(ddsPositive)),
                    Not(BeforeFirstDexAdministration(FourAtGte4)),
                    Not(BeforeFirstDexAdministration(FourAtPositive)),
                ),
            ),
            intervention_expr=IntraOrPostOperative(prophylacticDexmedetomidine),
            name="RecPlanSelectProphylacticDexAdministrationInPatsWithoutDementia",
            url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanSelectProphylacticDexAdministrationInPatsWithoutDementia",
            base_criterion=PatientsActiveDuringPeriod(),
        ),
        PopulationInterventionPairExpr(
            population_expr=And(AdultPatients(), anyDementiaBeforeSurgery),
            intervention_expr=IntraOrPostOperative(prophylacticDexmedetomidine),
            name="RecPlanSelectProphylacticDexAdministrationInPatsWithDementia",
            url="https://fhir.charite.de/digipod/PlanDefinition/RecPlanSelectProphylacticDexAdministrationInPatsWithDementia",
            base_criterion=PatientsActiveDuringPeriod(),
        ),
    ),
    base_criterion=PatientsActiveDuringPeriod(),
    name="RecCollProphylacticDexAdministrationAfterBalancingBenefitsVSSE",
    title="Recommendation Collection: Select 'prophylactic' if you administer dexmedetomidine intra- or postoperatively with the aim to prevent postoperative delirium after having balanced benefits and side effects in 'General Adult Surgical Patients With Dementia Preoperatively' or 'General Adult Surgical Patients Without Dementia Preoperatively nor Delirium Before Dexmedetomidine Administration'",
    url="https://fhir.charite.de/digipod/PlanDefinition/RecCollProphylacticDexAdministrationAfterBalancingBenefitsVSSE",
    version="0.4.0",
    description="Recommendation collection for adult patients getting dexmedetomidine during or after a surgical intervention of any type and independently of the type of anesthesia with the aim to prevent postoperative delirium (POD): Select 'prophylactic' if you administer dexmedetomidine with the aim to prevent postoperative delirium after having balanced benefits and side effects.",
    package_version="latest",
)
